### ISSUE TITLE
Fichiers .well-known pour serveur Matrix

### ISSUE THREAD

**Issue by johanricher** [multi-coop/multi-site-contents#23]
Nous avons provisionné un serveur Matrix et un client Element sur l'offre proposée par [EMS](https://ems.element.io/). Afin que ceux-ci utilisent le domaine `multi.coop` et que la fédération avec les autres serveurs Matrix fonctionne, il est nécessaire d'héberger sur `multi.coop` deux fichiers `.well-known`.

Sur `https://multi.coop/.well-known/matrix/server` : 
```
{
    "m.server": "multi-coop.ems.host:443"
}
```

Sur `https://multi.coop/.well-known/matrix/client` :
```
{
    "m.homeserver": {
        "base_url": "https://multi-coop.ems.host"
    },
    "m.identity_server": {
        "base_url": "https://vector.im"
    }
}
```

La doc détaillée est ici : https://ems-docs.element.io/EMS-Server-With-Custom-Domain.html?highlight=Well-Known#ems-server-with-custom-domain

Auparavant notre serveur Matrix était hébergé sur `matrix.jailbreak.paris`, associé au domaine `jailbreak.paris` grâce à ce fichier `.well-known` : https://jailbreak.paris/.well-known/matrix/server

Le site jailbreak.paris est un site statique hébergé sur Netlify, le fichier `.well-known` pouvait donc être mis directement dans le code ici : https://gitlab.com/jailbreak/jailbreak.paris/-/blob/master/static/.well-known/matrix/server

**Comment by JulienParis** [comment]
ah c chiant, ct pas le principe de `multi-site-app` de contenir des fichiers à l'usage d'un site en particulier car ça a pour but de rester générique. 

=> **Piste de solution** : faudrait pe faire une branche à part (genre `main-multi`) contenant les fichiers `.well-known` et qui serait déployée sur Netlify au lieu de la branche `main`. Je vais tester ça...

cf : https://answers.netlify.com/t/adding-a-verification-file-to-well-known-directory/5612

**Comment by JulienParis** [comment]
fichiers ajoutés sur la branche `main-multi` dans le dossier `static/.well-known` => https://github.com/multi-coop/multi-site-app/tree/main-multi/static/.well-known/matrix

pas encore testé le déploiement

**Comment by johanricher** [comment]
> ct pas le principe de multi-site-app de contenir des fichiers à l'usage d'un site en particulier car ça a pour but de rester générique.

Je dirais pas que c'est "à l'usage d'un site spécifique". Le besoin peut être le même pour héberger un favicon par exemple ou d'autres choses encore, de façon statique. Comment ce besoin générique est adressé actuellement ?

**Comment by JulienParis** [comment]
> Je dirais pas que c'est "à l'usage d'un site spécifique". Le besoin peut être le même pour héberger un favicon par exemple ou d'autres choses encore, de façon statique. Comment ce besoin générique est adressé actuellement ?

Bein déjà ct pas un besoin exprimé lors de la mise en place de notre site, quant à la question du favicon ou de fichiers statiques habituels ça peut être géré dynamiquement de façon générique dans un des composants de l’app (faudrait ajouter ce ticket d’ailleurs).

La solution que je propose pour le moment est en ce qui nous concerne de dédier une branche à notre propre usage, sinon il y a aussi la solution de forker et maintenir une synchronisation entre repo source (multi-site-app) et repos enfants… je brainstorm…

**Comment by johanricher** [comment]
> Bein déjà ct pas un besoin exprimé lors de la mise en place de notre site

En fait il n'y a pas eu de discussion et j'aurais sans doute eu des choses à dire (notamment sur la façon de gérer l'hybridation dynamique / statique puisque c'est un sujet sur lequel on a déjà eu à travailler) mais le fait est que le site répond sans conteste parfaitement à notre besoin actuel et ce n'est pas ça que je remets en question.

> pas encore testé le déploiement => https://app.netlify.com/sites/multi-website/deploys

Est-ce que ça veut dire qu'il n'y a qu'à relancer un build sur Netlify (ce que je peux faire) ou il y a d'autres choses à faire avant ?

**Comment by thoomasbro** [comment]
Question bête... on peut pas mettre matrix sur un sous domaine matrix.multi.coop ?

**Comment by johanricher** [comment]
Le serveur est sur `multi.ems.host` et les documents well known sont nécessaires sur  `multi.coop` pour associer le domaine à ce serveur, et de façon découvrable donc sur `domaine.com/.well-known/matrix/server`.

**Comment by JulienParis** [comment]
la PR #18 est mergée. Je clos cette issue
