### ISSUE TITLE
Ajout lien "Chattez avec Nous" vers canal Element

### ISSUE THREAD

**Issue by qloridant** [multi-coop/multi-site-contents#35]
Référencer sur le site notre canal publique sur Element.
J'imagine ça bien sur la page "Contact"

**Comment by JulienParis** [comment]
on pourrait aussi ajouter un lien dans les icones du footer... je regarde ça pour proposer une PR

**Comment by JulienParis** [comment]
@qloridant tu pourrais copier ici le lien à mentionner pour renvoyer vers notre matrix et notre salon public pendant que je prépare la PR ?

**Comment by JulienParis** [comment]
je propose de clore cette issue car on a bien une icone qui renvoie vers notre chat dans le footer

![Capture d’écran 2022-07-09 à 11 20 36](https://user-images.githubusercontent.com/21986727/178099859-a3443dee-ea38-409a-a6ff-92df5730b906.png)

**Comment by JulienParis** [comment]
ça me semble clôturable, je me permets de clôturer
