### ISSUE TITLE
Chargement du logo en page d'accueil long

### ISSUE THREAD

**Issue by arobase-che** [multi-coop/multi-site-contents#43]
Bonjour,

Le chargement du logo Multi sur la page d'accueil est suspicieusement long.

![2022-04-28-011219_1920x1080_scrot](https://user-images.githubusercontent.com/2202307/165646529-97f68d0a-8744-4aa4-89b1-d2a34b3ac43a.png)

Après une rapide étude. Le problème semble venir d'ici:

https://github.com/multi-coop/multi-site-contents/blob/8329794942a042f528ab48337fafd11fd9771b93/texts/landing/landing-head-fr.md?plain=1#L7

Sachant que le logo est affichée instantanément en haut à gauche de chaque page et que c'est la même image (même définition). 
Peut-être y aurait-il moyen d'utiliser la même image ?  
Je suppose que ce n'est pas aussi simple que `./images/logos/logo-multi-003.png` ? GitHub Pages comprendrait ?

Sinon, `/multi-coop/multi-site-contents/main/images/logos/logo-multi-003.png` me semble “correcte” même si on retrouve le nom du dépôt et de l'utilisateur.

Pour reproduire, il faut forcer le rechargement ||Ctrl|| + ||F5|| ou désactiver le cache.

**Comment by JulienParis** [comment]
@arobase-che merci pour ce retour, même si je reviens vers vous bien tard !!!

Vous aviez totalement raison, ça n'avait pas vraiment de sens de pointer vers hackmd alors que l'image est bien d'ores et déjà sur notre repo.

J'ai modifié l'url pointant vers l'image de notre logo afin qu'elle point vers sa source sur github dans le [md correspondant](https://github.com/multi-coop/multi-site-contents/blob/main/texts/landing/landing-head-fr.md?plain=1), et il y a du mieux tout de même :) 

```
![](https://raw.githubusercontent.com/multi-coop/multi-site-contents/main/images/logos/logo-multi-003.png)
```

Encore merci !

**Comment by arobase-che** [comment]
Pas de soucis, c'est surtout pour vous. Je suis content d'avoir pu aider.

De rien et à une prochaine fois. \o
