### ISSUE TITLE
Ajout Information Clients

### ISSUE THREAD

**Issue by qloridant** [multi-coop/multi-site-contents#44]
A multi, nous avons des "beaux" clients : DINUM, ODF, MEDNUM...

Je propose de mettre en avant qquns de ces client sur la page d'accueil pour gagner en crédibilité.

**Comment by JulienParis** [comment]
ça vous irait une page d'accueil de ce genre ?  cf https://github.com/multi-coop/multi-site-contents/pull/53

- logos plus ou moins groupés par importance qu'on leur donne et familles d'acteurs
- logoo + hyperlien

![Capture d’écran 2022-07-09 à 11 01 13](https://user-images.githubusercontent.com/21986727/178099291-b5e5cf6b-6ec0-4121-9da6-b4774e22fd90.png)


J'ai oublié personne ?

**Comment by qloridant** [comment]
C'est joli !
Par contre la plupart ne sont pas partenaires mais clients.
Peut-être utiliser la phrase : Ils travaillent avec nous

**Comment by JulienParis** [comment]
> C'est joli ! Par contre la plupart ne sont pas partenaires mais clients. Peut-être utiliser la phrase : Ils travaillent avec nous

done : https://github.com/multi-coop/multi-site-contents/pull/53/files#diff-10fd8f0e01f57dbd30418b0b479e97a33841531c64b62d8ee61186914b90f101
