### ISSUE TITLE
Enlever la section Alumni ?

### ISSUE THREAD

**Issue by qloridant** [multi-coop/multi-site-contents#65]
Notre alumni ne veut plus apparaître dans la page Équipe, la section Alumni est vide.
Pour le moment il y a juste une fiche vide.

Proposition : 
- Enlever entièrement la section
- La laisser blanche

**Comment by johanricher** [comment]
Si la deuxième proposition est de laisser la page telle quelle, ça me paraît pas souhaitable :

![image](https://user-images.githubusercontent.com/10212787/204032333-b5e01f90-4ead-4d9c-b7d3-37d4357b172f.png)


La première proposition me paraît la meilleure et consisterait à [revert](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request) la PR #92 (avec l'inconvénient qu'il faudra rétablir les commits qui ne concernent pas les alumni et qui ont été mélangés à cette PR).
